#!/bin/bash
find ./ -name "*.cpp" -o -name "*.c" -o -name "*.h" > cscope.files
cscope -b
CSCOPE_DB=$PWD/cscope.out; export CSCOPE_DB
echo $CSCOPE_DB
#ctags -R --c++-kinds=+p --fields=+iaS --extra=+q
ctags -aR --fields=+ianS --extra=+q -o tags
